[package]
name = "tui-nonogram"
version = "0.1.0"
edition = "2024"
description = "A nonogram game for the terminal."
license = "MIT"
repository = "https://github.com/aayushprime/tui-nonogram"

[dependencies]
ratatui = "0.26.1"
crossterm = "0.27.0"
color-eyre = "0.6.1"
rand = "0.8.5"
